In [1]:
import keras

C:\Users\virendra\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
import tensorflow

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('ANN\Artificial_Neural_Networks\Churn_Modelling.csv')

In [9]:
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [5]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [7]:
type(X)

numpy.ndarray

In [8]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

In [261]:
X=X[:, 1:]

In [262]:
# splitting dataset into trainin and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [12]:
#feature scalling
from sklearn.preprocessing import StandardScaler

In [263]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [15]:
sc=StandardScaler()
x_train=sc.fit_transform(X_train)
x_test=sc.transform(X_test)

In [16]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=11)
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=11, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [17]:
y_pre=clf.predict(x_test)

In [229]:
x_test.shape

(2000, 11)

In [19]:
from sklearn.model_selection import cross_val_score as csv

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pre)

In [21]:
y_pre=(y_pre>0.5)
unique_elements, counts_elements = np.unique(y_pre, return_counts=True)




 Predicting the Test set results
y_pred = classifier.predict(X_test)

 Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [22]:
cm

array([[1487,  108],
       [ 185,  220]], dtype=int64)

In [23]:
1696/2000

0.848

# part 2 ANN

In [24]:
from keras import Sequential

In [25]:
from keras.layers import Dense

In [ ]:
from keras.layers import Dropout

In [26]:
#initializing an ANN

In [232]:
classifier = Sequential()

In [233]:
#adding input layer to classier and the first input layer 
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))

C:\Users\virendra\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [ ]:
classifier.add(Dropout(p=0.1))

In [234]:
classifier

In [235]:
#adding the second hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))

C:\Users\virendra\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [236]:
#addu=ing the output layer
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))

C:\Users\virendra\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [237]:
#compiling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [238]:
#fitting the ANN to the Training set
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

C:\Users\virendra\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 3s 397us/step - loss: 0.4797 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.4276 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 159us/step - loss: 0.4222 - acc: 0.7999
Epoch 4/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.4182 - acc: 0.8214
Epoch 5/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4162 - acc: 0.8266
Epoch 6/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.4142 - acc: 0.8297
Epoch 7/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.4129 - acc: 0.8314
Epoch 8/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.4114 - acc: 0.8314
Epoch 9/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.4101 - acc: 0.8331
Epoch 10/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.4094 - acc: 0.8326

In [35]:
#part 3-Making the prediction ptobability

In [239]:
X_test.shape

(2000, 11)

In [240]:
y_pred=classifier.predict(X_test)

In [241]:
y_pred=(y_pred>0.5)

In [242]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [243]:
cm

array([[1550,   45],
       [ 270,  135]], dtype=int64)

In [244]:
(1545+141)/2000

0.843

In [41]:
#part4 predict single member decisiion

In [197]:
cred={
    "yup":0.0,
    "Geography":0,
    "Credit Score": 600,
    "Gender": 1,
    "Age": 40,
    "Tenure": 3,
    "Balance": 60000,
    "Number of Products": 2,
    "Does this customer have a credit card ": "Yes",
    "Is this customer an Active Member": "Yes",
    "Estimated Salary":50000}
    

In [198]:
(cred.keys())

dict_keys(['yup', 'Geography', 'Credit Score', 'Gender', 'Age', 'Tenure', 'Balance', 'Number of Products', 'Does this customer have a credit card ', 'Is this customer an Active Member', 'Estimated Salary'])

In [209]:
ke=[]
val=[]
c=0
for key, value in cred.items():
    ke.append(key)
    val.append(value)
    c+=1

In [200]:
people=[]
for i in range(len(ke)):
    people.append([ke[i],val[i]])


In [201]:
people

[['yup', 0.0],
 ['Geography', 0],
 ['Credit Score', 600],
 ['Gender', 1],
 ['Age', 40],
 ['Tenure', 3],
 ['Balance', 60000],
 ['Number of Products', 2],
 ['Does this customer have a credit card ', 'Yes'],
 ['Is this customer an Active Member', 'Yes'],
 ['Estimated Salary', 50000]]

In [210]:
ke

['yup',
 'Geography',
 'Credit Score',
 'Gender',
 'Age',
 'Tenure',
 'Balance',
 'Number of Products',
 'Does this customer have a credit card ',
 'Is this customer an Active Member',
 'Estimated Salary']

In [211]:
X=np.array(ke).reshape(1,11)
y=np.array(val).reshape(1,11)

In [212]:
y

array([['0.0', '0', '600', '1', '40', '3', '60000', '2', 'Yes', 'Yes',
        '50000']], dtype='<U32')

In [220]:
df = pd.DataFrame(y,columns=ke)
df

yup Geography Credit Score Gender Age Tenure Balance Number of Products  \
0  0.0         0          600      1  40      3   60000                  2   

  Does this customer have a credit card  Is this customer an Active Member  \
0                                    Yes                               Yes   

  Estimated Salary  
0            50000

In [221]:
df=np.array(df)
df.shape

(1, 11)

In [215]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_df_1 = LabelEncoder()
df[:, 2] = labelencoder_df_1.fit_transform(df[:, 2])


In [222]:
labelencoder_df_2 = LabelEncoder()
df[:, 9] = labelencoder_df_2.fit_transform(df[:, 9])
labelencoder_df_3 = LabelEncoder()
df[:, 8] = labelencoder_df_3.fit_transform(df[:, 8])

In [223]:
XX=df
XX

array([['0.0', '0', '600', '1', '40', '3', '60000', '2', 0, 0, '50000']],
      dtype=object)

In [224]:
onehotencoder = OneHotEncoder(categorical_features = [1])
XX = onehotencoder.fit_transform(XX).toarray()
XX

array([[1.e+00, 0.e+00, 6.e+02, 1.e+00, 4.e+01, 3.e+00, 6.e+04, 2.e+00,
        0.e+00, 0.e+00, 5.e+04]])

In [225]:
sc.transform(XX)

array([[ 1.00000000e+00, -1.09065534e-16,  6.00000000e+02,
         1.00000000e+00,  4.00000000e+01,  3.00000000e+00,
         6.00000000e+04,  2.00000000e+00,  1.31034072e-16,
         2.78665979e-17,  5.00000000e+04]])

In [246]:
npred=classifier.predict(XX)

In [247]:
npred=(npred>0.5)

In [248]:
npred

array([[False]])

In [253]:
#Evaluating the ANN

In [250]:
from keras.wrappers.scikit_learn import KerasClassifier

In [252]:
from sklearn.model_selection import cross_val_score

In [254]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))
    classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))
    classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))
    classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return classifier

In [255]:
classifier=KerasClassifier(build_fn=build_classifier,batch_size=10,nb_epoch=100)

In [ ]:
accuracies=cross_val_score(estimator=classifier,X=X_train,y=y_train,cv=10,n_jobs=-1)

In [ ]:
accuracies.mean()

In [ ]:
#parameter tuning